export interface Emoji {
  char: string;
  name: string;
  keywords: string[];
  category: string;
  subcategory: string;
}

export const emojiCategories = [
  { id: 'smileys', name: 'Smileys', icon: '😀' },
  { id: 'people', name: 'People', icon: '👤' },
  { id: 'animals', name: 'Animals', icon: '🐱' },
  { id: 'food', name: 'Food', icon: '🍎' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'travel', name: 'Travel', icon: '✈️' },
  { id: 'objects', name: 'Objects', icon: '💡' },
  { id: 'symbols', name: 'Symbols', icon: '❤️' },
];

export const emojis: Emoji[] = [
  { char: '😀', name: 'grinning face', keywords: ['grin', 'happy', 'smile', 'face'], category: 'smileys', subcategory: 'face' },
  { char: '😃', name: 'grinning face with big eyes', keywords: ['grin', 'happy', 'smile', 'eyes', 'face'], category: 'smileys', subcategory: 'face' },
  { char: '😄', name: 'grinning face with smiling eyes', keywords: ['grin', 'happy', 'smile', 'eyes', 'face'], category: 'smileys', subcategory: 'face' },
  { char: '😁', name: 'beaming face with smiling eyes', keywords: ['grin', 'happy', 'smile', 'eyes', 'face', 'proud'], category: 'smileys', subcategory: 'face' },
  { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy', 'smile', 'face', 'squint'], category: 'smileys', subcategory: 'face' },
  { char: '😅', name: 'grinning face with sweat', keywords: ['sweat', 'smile', 'relief', 'face', 'hot'], category: 'smileys', subcategory: 'face' },
  { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'lol', 'face', 'floor'], category: 'smileys', subcategory: 'face' },
  { char: '😂', name: 'face with tears of joy', keywords: ['joy', 'laugh', 'cry', 'tears', 'face'], category: 'smileys', subcategory: 'face' },
  { char: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy', 'face', 'slight'], category: 'smileys', subcategory: 'face' },
  { char: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'happy', 'eyes', 'face', 'blush'], category: 'smileys', subcategory: 'face' },
  { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'smile', 'face', 'heaven', 'good'], category: 'smileys', subcategory: 'face' },
  { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'hearts', 'face', 'crush', 'heart'], category: 'smileys', subcategory: 'face' },
  { char: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'heart', 'eyes', 'face', 'crush'], category: 'smileys', subcategory: 'face' },
  { char: '🤩', name: 'star-struck', keywords: ['star', 'eyes', 'face', 'excited', 'famous'], category: 'smileys', subcategory: 'face' },
  { char: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'face', 'blow', 'muah'], category: 'smileys', subcategory: 'face' },
  { char: '😗', name: 'kissing face', keywords: ['kiss', 'face', 'love'], category: 'smileys', subcategory: 'face' },
  { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'face', 'closed', 'eyes'], category: 'smileys', subcategory: 'face' },
  { char: '😋', name: 'face savoring food', keywords: ['tasty', 'food', 'lick', 'face', 'yummy'], category: 'smileys', subcategory: 'face' },
  { char: '😛', name: 'face with tongue', keywords: ['tongue', 'face', 'playful', 'lick'], category: 'smileys', subcategory: 'face' },
  { char: '😜', name: 'winking face with tongue', keywords: ['tongue', 'wink', 'face', 'playful', 'silly'], category: 'smileys', subcategory: 'face' },
  { char: '🤪', name: 'zany face', keywords: ['zany', 'face', 'crazy', 'wacky', 'silly'], category: 'smileys', subcategory: 'face' },
  { char: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'squint', 'face', 'playful'], category: 'smileys', subcategory: 'face' },
  { char: '🤑', name: 'money-mouth face', keywords: ['money', 'face', 'rich', 'dollar'], category: 'smileys', subcategory: 'face' },
  { char: '🤗', name: 'hugging face', keywords: ['hug', 'face', 'cuddle', 'huggy'], category: 'smileys', subcategory: 'face' },
  { char: '🤭', name: 'face with hand over mouth', keywords: ['hand', 'mouth', 'face', 'shh', 'secret'], category: 'smileys', subcategory: 'face' },
  { char: '🤫', name: 'shushing face', keywords: ['shush', 'face', 'quiet', 'hush'], category: 'smileys', subcategory: 'face' },
  { char: '🤔', name: 'thinking face', keywords: ['think', 'face', 'hmm', 'wonder', 'ponder'], category: 'smileys', subcategory: 'face' },
  { char: '🤐', name: 'zipper-mouth face', keywords: ['zipper', 'mouth', 'face', 'silence', 'quiet'], category: 'smileys', subcategory: 'face' },
  { char: '🤨', name: 'face with raised eyebrow', keywords: ['eyebrow', 'face', 'suspicious', 'doubt'], category: 'smileys', subcategory: 'face' },
  { char: '😐', name: 'neutral face', keywords: ['neutral', 'face', 'meh', 'blank'], category: 'smileys', subcategory: 'face' },
  { char: '😑', name: 'expressionless face', keywords: ['expressionless', 'face', 'meh', 'blank'], category: 'smileys', subcategory: 'face' },
  { char: '😶', name: 'face without mouth', keywords: ['no mouth', 'face', 'silent', 'quiet'], category: 'smileys', subcategory: 'face' },
  { char: '😏', name: 'smirking face', keywords: ['smirk', 'face', 'sly', 'grin'], category: 'smileys', subcategory: 'face' },
  { char: '😒', name: 'unamused face', keywords: ['unamused', 'face', 'bored', 'meh'], category: 'smileys', subcategory: 'face' },
  { char: '🙄', name: 'face with rolling eyes', keywords: ['roll', 'eyes', 'face', 'eyeroll', 'tired'], category: 'smileys', subcategory: 'face' },
  { char: '😬', name: 'grimacing face', keywords: ['grimace', 'face', 'teeth', 'nervous'], category: 'smileys', subcategory: 'face' },
  { char: '🤥', name: 'lying face', keywords: ['lie', 'liar', 'face', 'pinocchio', 'false'], category: 'smileys', subcategory: 'face' },
  { char: '😌', name: 'relieved face', keywords: ['relieved', 'face', 'phew', 'peace'], category: 'smileys', subcategory: 'face' },
  { char: '😔', name: 'pensive face', keywords: ['pensive', 'face', 'sad', 'thoughtful'], category: 'smileys', subcategory: 'face' },
  { char: '😪', name: 'sleepy face', keywords: ['sleep', 'face', 'tired', 'zzz'], category: 'smileys', subcategory: 'face' },
  { char: '🤤', name: 'drooling face', keywords: ['drool', 'face', 'hungry', 'slobber'], category: 'smileys', subcategory: 'face' },
  { char: '😴', name: 'sleeping face', keywords: ['sleep', 'face', 'zzz', 'nap'], category: 'smileys', subcategory: 'face' },
  { char: '😷', name: 'face with medical mask', keywords: ['mask', 'face', 'sick', 'ill', 'covid'], category: 'smileys', subcategory: 'face' },
  { char: '🤒', name: 'face with thermometer', keywords: ['thermometer', 'face', 'sick', 'ill', 'fever'], category: 'smileys', subcategory: 'face' },
  { char: '🤕', name: 'face with bandage', keywords: ['bandage', 'face', 'injured', 'hurt', 'wound'], category: 'smileys', subcategory: 'face' },
  { char: '🤢', name: 'nauseated face', keywords: ['nausea', 'face', 'sick', 'gross', 'vomit'], category: 'smileys', subcategory: 'face' },
  { char: '🤮', name: 'face vomiting', keywords: ['vomit', 'face', 'sick', 'gross', 'barf'], category: 'smileys', subcategory: 'face' },
  { char: '🤧', name: 'sneezing face', keywords: ['sneeze', 'face', 'sick', 'gesundheit'], category: 'smileys', subcategory: 'face' },
  { char: '🥵', name: 'hot face', keywords: ['hot', 'face', 'heat', 'sweat', 'burning'], category: 'smileys', subcategory: 'face' },
  { char: '🥶', name: 'cold face', keywords: ['cold', 'face', 'freezing', 'ice', 'chill'], category: 'smileys', subcategory: 'face' },
  { char: '🥴', name: 'woozy face', keywords: ['woozy', 'face', 'dizzy', 'groggy'], category: 'smileys', subcategory: 'face' },
  { char: '😵', name: 'dizzy face', keywords: ['dizzy', 'face', 'spun', 'knocked out'], category: 'smileys', subcategory: 'face' },
  { char: '🤯', name: 'exploding head', keywords: ['explode', 'head', 'mind blown', 'shocked'], category: 'smileys', subcategory: 'face' },
  { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'hat', 'face', 'yeehaw'], category: 'smileys', subcategory: 'face' },
  { char: '🥳', name: 'partying face', keywords: ['party', 'face', 'celebrate', 'birthday'], category: 'smileys', subcategory: 'face' },
  { char: '🥺', name: 'pleading face', keywords: ['plead', 'face', 'puppy eyes', 'beg', 'mercy'], category: 'smileys', subcategory: 'face' },
  { char: '🥹', name: 'face holding back tears', keywords: ['tears', 'hold back', 'face', 'emotional'], category: 'smileys', subcategory: 'face' },
  { char: '😮', name: 'face with open mouth', keywords: ['open mouth', 'face', 'wow', 'surprise'], category: 'smileys', subcategory: 'face' },
  { char: '😯', name: 'hushed face', keywords: ['hushed', 'face', 'surprise', 'shh'], category: 'smileys', subcategory: 'face' },
  { char: '😱', name: 'face screaming in fear', keywords: ['scream', 'fear', 'face', 'horror', 'shocked'], category: 'smileys', subcategory: 'face' },
  { char: '😨', name: 'fearful face', keywords: ['fear', 'face', 'scared', 'nervous'], category: 'smileys', subcategory: 'face' },
  { char: '😰', name: 'anxious face with sweat', keywords: ['anxious', 'face', 'nervous', 'worry'], category: 'smileys', subcategory: 'face' },
  { char: '😥', name: 'sad but relieved face', keywords: ['sad', 'relieved', 'face', 'disappointed'], category: 'smileys', subcategory: 'face' },
  { char: '😢', name: 'crying face', keywords: ['cry', 'tears', 'face', 'sad', 'sob'], category: 'smileys', subcategory: 'face' },
  { char: '😭', name: 'loudly crying face', keywords: ['cry', 'tears', 'face', 'sad', 'sob', 'loud'], category: 'smileys', subcategory: 'face' },
  { char: '😤', name: 'face with steam from nose', keywords: ['steam', 'nose', 'face', 'angry', 'frustrated'], category: 'smileys', subcategory: 'face' },
  { char: '😡', name: 'pouting face', keywords: ['pout', 'anger', 'face', 'mad', 'upset'], category: 'smileys', subcategory: 'face' },
  { char: '😠', name: 'angry face', keywords: ['anger', 'face', 'mad', 'upset'], category: 'smileys', subcategory: 'face' },
  { char: '🤬', name: 'face with symbols over mouth', keywords: ['cursing', 'face', 'swear', 'profanity'], category: 'smileys', subcategory: 'face' },
  { char: '😈', name: 'smiling face with horns', keywords: ['devil', 'horns', 'face', 'smile', 'evil'], category: 'smileys', subcategory: 'face' },
  { char: '👿', name: 'angry face with horns', keywords: ['devil', 'horns', 'face', 'anger', 'evil'], category: 'smileys', subcategory: 'face' },
  { char: '💀', name: 'skull', keywords: ['skull', 'death', 'bone', 'dead'], category: 'smileys', subcategory: 'face' },
  { char: '☠️', name: 'skull and crossbones', keywords: ['skull', 'crossbones', 'death', 'poison'], category: 'smileys', subcategory: 'face' },
  { char: '💩', name: 'pile of poo', keywords: ['poo', 'poop', 'shit', 'dung'], category: 'smileys', subcategory: 'face' },
  { char: '🤡', name: 'clown face', keywords: ['clown', 'face', 'funny'], category: 'smileys', subcategory: 'face' },
  { char: '👻', name: 'ghost', keywords: ['ghost', 'spirit', 'spooky', 'halloween'], category: 'smileys', subcategory: 'face' },
  { char: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space', 'extraterrestrial'], category: 'smileys', subcategory: 'face' },
  { char: '🤖', name: 'robot', keywords: ['robot', 'bot', 'machine', 'android'], category: 'smileys', subcategory: 'face' },
  { char: '💋', name: 'kiss mark', keywords: ['kiss', 'lip', 'mark', 'love'], category: 'smileys', subcategory: 'emotion' },
  { char: '💌', name: 'love letter', keywords: ['love', 'letter', 'mail', 'heart'], category: 'smileys', subcategory: 'emotion' },
  { char: '💘', name: 'heart with arrow', keywords: ['heart', 'arrow', 'love', 'cupid'], category: 'smileys', subcategory: 'emotion' },
  { char: '💝', name: 'heart with ribbon', keywords: ['heart', 'ribbon', 'gift', 'love'], category: 'smileys', subcategory: 'emotion' },
  { char: '💖', name: 'sparkling heart', keywords: ['sparkle', 'heart', 'love', 'shiny'], category: 'smileys', subcategory: 'emotion' },
  { char: '💗', name: 'growing heart', keywords: ['growing', 'heart', 'love', 'pulse'], category: 'smileys', subcategory: 'emotion' },
  { char: '💓', name: 'beating heart', keywords: ['beating', 'heart', 'love', 'pulse'], category: 'smileys', subcategory: 'emotion' },
  { char: '💞', name: 'revolving hearts', keywords: ['revolving', 'heart', 'love', 'cycle'], category: 'smileys', subcategory: 'emotion' },
  { char: '💕', name: 'two hearts', keywords: ['two', 'heart', 'love', 'couple'], category: 'smileys', subcategory: 'emotion' },
  { char: '💟', name: 'heart decoration', keywords: ['heart', 'decoration', 'love', 'ornament'], category: 'smileys', subcategory: 'emotion' },
  { char: '❣️', name: 'heart exclamation', keywords: ['heart', 'exclamation', 'love', 'mark'], category: 'smileys', subcategory: 'emotion' },
  { char: '💔', name: 'broken heart', keywords: ['broken', 'heart', 'sad', 'breakup'], category: 'smileys', subcategory: 'emotion' },
  { char: '❤️', name: 'red heart', keywords: ['red', 'heart', 'love', 'like'], category: 'smileys', subcategory: 'emotion' },
  { char: '🧡', name: 'orange heart', keywords: ['orange', 'heart', 'love'], category: 'smileys', subcategory: 'emotion' },
  { char: '💛', name: 'yellow heart', keywords: ['yellow', 'heart', 'love', 'friend'], category: 'smileys', subcategory: 'emotion' },
  { char: '💚', name: 'green heart', keywords: ['green', 'heart', 'love', 'envy'], category: 'smileys', subcategory: 'emotion' },
  { char: '💙', name: 'blue heart', keywords: ['blue', 'heart', 'love', 'trust'], category: 'smileys', subcategory: 'emotion' },
  { char: '💜', name: 'purple heart', keywords: ['purple', 'heart', 'love', 'royal'], category: 'smileys', subcategory: 'emotion' },
  { char: '🖤', name: 'black heart', keywords: ['black', 'heart', 'love', 'dark'], category: 'smileys', subcategory: 'emotion' },
  { char: '🤍', name: 'white heart', keywords: ['white', 'heart', 'pure', 'peace'], category: 'smileys', subcategory: 'emotion' },
  { char: '🤎', name: 'brown heart', keywords: ['brown', 'heart', 'earth', 'cozy'], category: 'smileys', subcategory: 'emotion' },
  { char: '💯', name: 'hundred points', keywords: ['100', 'points', 'score', 'perfect', 'hundred'], category: 'smileys', subcategory: 'emotion' },
  { char: '💢', name: 'anger symbol', keywords: ['anger', 'symbol', 'angry', 'mood'], category: 'smileys', subcategory: 'emotion' },
  { char: '💥', name: 'collision', keywords: ['collision', 'boom', 'explode', 'impact'], category: 'smileys', subcategory: 'emotion' },
  { char: '💫', name: 'dizzy', keywords: ['dizzy', 'stars', 'spin', 'dazzed'], category: 'smileys', subcategory: 'emotion' },
  { char: '💦', name: 'sweat droplets', keywords: ['sweat', 'droplet', 'water', 'wet'], category: 'smileys', subcategory: 'emotion' },
  { char: '💨', name: 'dashing away', keywords: ['dash', 'wind', 'fast', 'whoosh'], category: 'smileys', subcategory: 'emotion' },
  { char: '🕳️', name: 'hole', keywords: ['hole', 'pit', 'empty', 'black'], category: 'smileys', subcategory: 'emotion' },
  { char: '💣', name: 'bomb', keywords: ['bomb', 'boom', 'explosive', 'danger'], category: 'smileys', subcategory: 'emotion' },
  { char: '💬', name: 'speech balloon', keywords: ['speech', 'balloon', 'talk', 'bubble'], category: 'smileys', subcategory: 'emotion' },
  { char: '🗨️', name: 'left speech bubble', keywords: ['speech', 'bubble', 'talk', 'dialogue'], category: 'smileys', subcategory: 'emotion' },
  { char: '🗯️', name: 'right anger bubble', keywords: ['anger', 'bubble', 'mad', 'speech'], category: 'smileys', subcategory: 'emotion' },
  { char: '💭', name: 'thought balloon', keywords: ['thought', 'bubble', 'think', 'wonder'], category: 'smileys', subcategory: 'emotion' },
  { char: '💤', name: 'zzz', keywords: ['zzz', 'sleep', 'nap', 'rest'], category: 'smileys', subcategory: 'emotion' },
  
  // People
  { char: '👋', name: 'waving hand', keywords: ['wave', 'hand', 'hi', 'bye', 'hello'], category: 'people', subcategory: 'hand' },
  { char: '🤚', name: 'raised back of hand', keywords: ['raised', 'hand', 'back', 'stop'], category: 'people', subcategory: 'hand' },
  { char: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'fingers', 'splayed', 'high five'], category: 'people', subcategory: 'hand' },
  { char: '✋', name: 'raised hand', keywords: ['raised', 'hand', 'high five', 'stop'], category: 'people', subcategory: 'hand' },
  { char: '👌', name: 'OK hand', keywords: ['ok', 'hand', 'okay', 'good'], category: 'people', subcategory: 'hand' },
  { char: '🤌', name: 'pinched fingers', keywords: ['pinch', 'fingers', 'small', 'tiny'], category: 'people', subcategory: 'hand' },
  { char: '🤏', name: 'pinching hand', keywords: ['pinch', 'hand', 'small', 'tiny'], category: 'people', subcategory: 'hand' },
  { char: '✌️', name: 'victory hand', keywords: ['victory', 'hand', 'peace', 'v'], category: 'people', subcategory: 'hand' },
  { char: '🤞', name: 'crossed fingers', keywords: ['crossed', 'fingers', 'hope', 'luck'], category: 'people', subcategory: 'hand' },
  { char: '🤟', name: 'love-you gesture', keywords: ['love', 'hand', 'ILY', 'sign'], category: 'people', subcategory: 'hand' },
  { char: '🤘', name: 'horns sign', keywords: ['horns', 'hand', 'rock', 'metal'], category: 'people', subcategory: 'hand' },
  { char: '🤙', name: 'call me hand', keywords: ['call', 'hand', 'phone', 'ring'], category: 'people', subcategory: 'hand' },
  { char: '👈', name: 'backhand index pointing left', keywords: ['left', 'point', 'finger', 'backhand'], category: 'people', subcategory: 'hand' },
  { char: '👉', name: 'backhand index pointing right', keywords: ['right', 'point', 'finger', 'backhand'], category: 'people', subcategory: 'hand' },
  { char: '👆', name: 'backhand index pointing up', keywords: ['up', 'point', 'finger', 'backhand'], category: 'people', subcategory: 'hand' },
  { char: '🖕', name: 'middle finger', keywords: ['middle', 'finger', 'rude', 'offensive'], category: 'people', subcategory: 'hand' },
  { char: '👇', name: 'backhand index pointing down', keywords: ['down', 'point', 'finger', 'backhand'], category: 'people', subcategory: 'hand' },
  { char: '👍', name: 'thumbs up', keywords: ['thumbs up', 'like', 'good', 'approve'], category: 'people', subcategory: 'hand' },
  { char: '👎', name: 'thumbs down', keywords: ['thumbs down', 'dislike', 'bad', 'down'], category: 'people', subcategory: 'hand' },
  { char: '✊', name: 'raised fist', keywords: ['raised', 'fist', 'power', 'strength'], category: 'people', subcategory: 'hand' },
  { char: '🤛', name: 'left-facing fist', keywords: ['left', 'fist', 'punch'], category: 'people', subcategory: 'hand' },
  { char: '🤜', name: 'right-facing fist', keywords: ['right', 'fist', 'punch'], category: 'people', subcategory: 'hand' },
  { char: '👏', name: 'clapping hands', keywords: ['clap', 'hands', 'applause', 'praise'], category: 'people', subcategory: 'hand' },
  { char: '🙌', name: 'raising hands', keywords: ['raise', 'hands', 'celebrate', 'praise'], category: 'people', subcategory: 'hand' },
  { char: '👐', name: 'open hands', keywords: ['open', 'hands', 'hug', 'welcome'], category: 'people', subcategory: 'hand' },
  { char: '🤲', name: 'palms up together', keywords: ['palms', 'together', 'pray', 'cup'], category: 'people', subcategory: 'hand' },
  { char: '🤝', name: 'handshake', keywords: ['handshake', 'deal', 'agreement', 'greet'], category: 'people', subcategory: 'hand' },
  { char: '🙏', name: 'folded hands', keywords: ['folded', 'hands', 'pray', 'please', 'thank'], category: 'people', subcategory: 'hand' },
  { char: '💅', name: 'nail polish', keywords: ['nail', 'polish', 'beauty', 'manicure'], category: 'people', subcategory: 'body' },
  { char: '🤳', name: 'selfie', keywords: ['selfie', 'phone', 'camera', 'self'], category: 'people', subcategory: 'body' },
  { char: '💪', name: 'flexed biceps', keywords: ['flex', 'biceps', 'muscle', 'strong'], category: 'people', subcategory: 'body' },
  { char: '🦾', name: 'mechanical arm', keywords: ['mechanical', 'arm', 'robot', 'prosthetic'], category: 'people', subcategory: 'body' },
  { char: '🦿', name: 'mechanical leg', keywords: ['mechanical', 'leg', 'robot', 'prosthetic'], category: 'people', subcategory: 'body' },
  { char: '🦵', name: 'leg', keywords: ['leg', 'kick', 'limb'], category: 'people', subcategory: 'body' },
  { char: '🦶', name: 'foot', keywords: ['foot', 'kick', 'step'], category: 'people', subcategory: 'body' },
  { char: '👂', name: 'ear', keywords: ['ear', 'hear', 'listen'], category: 'people', subcategory: 'body' },
  { char: '🦻', name: 'ear with hearing aid', keywords: ['ear', 'hearing', 'aid', 'listen'], category: 'people', subcategory: 'body' },
  { char: '👃', name: 'nose', keywords: ['nose', 'smell', 'scent'], category: 'people', subcategory: 'body' },
  { char: '🧠', name: 'brain', keywords: ['brain', 'mind', 'think', 'smart'], category: 'people', subcategory: 'body' },
  { char: '🦷', name: 'tooth', keywords: ['tooth', 'dentist', 'dental'], category: 'people', subcategory: 'body' },
  { char: '🦴', name: 'bone', keywords: ['bone', 'skeleton', 'dog'], category: 'people', subcategory: 'body' },
  { char: '👀', name: 'eyes', keywords: ['eyes', 'look', 'see', 'watch'], category: 'people', subcategory: 'body' },
  { char: '👁️', name: 'eye', keywords: ['eye', 'see', 'look', 'watch'], category: 'people', subcategory: 'body' },
  { char: '👅', name: 'tongue', keywords: ['tongue', 'taste', 'lick', 'mouth'], category: 'people', subcategory: 'body' },
  { char: '👄', name: 'mouth', keywords: ['mouth', 'lip', 'kiss', 'speak'], category: 'people', subcategory: 'body' },
  { char: '👶', name: 'baby', keywords: ['baby', 'child', 'infant', 'young'], category: 'people', subcategory: 'person' },
  { char: '👧', name: 'girl', keywords: ['girl', 'child', 'kid', 'young'], category: 'people', subcategory: 'person' },
  { char: '👦', name: 'boy', keywords: ['boy', 'child', 'kid', 'young'], category: 'people', subcategory: 'person' },
  { char: '👨', name: 'man', keywords: ['man', 'male', 'guy', 'dad'], category: 'people', subcategory: 'person' },
  { char: '👩', name: 'woman', keywords: ['woman', 'female', 'lady', 'mom'], category: 'people', subcategory: 'person' },
  { char: '🧔', name: 'person beard', keywords: ['beard', 'man', 'facial hair'], category: 'people', subcategory: 'person' },
  { char: '👴', name: 'old man', keywords: ['old', 'man', 'elderly', 'senior'], category: 'people', subcategory: 'person' },
  { char: '👵', name: 'old woman', keywords: ['old', 'woman', 'elderly', 'senior'], category: 'people', subcategory: 'person' },
  
  // Animals
  { char: '🐱', name: 'cat', keywords: ['cat', 'kitty', 'kitten', 'meow'], category: 'animals', subcategory: 'animal' },
  { char: '🐶', name: 'dog', keywords: ['dog', 'puppy', 'pup', 'woof'], category: 'animals', subcategory: 'animal' },
  { char: '🐭', name: 'mouse', keywords: ['mouse', 'cheese', 'small'], category: 'animals', subcategory: 'animal' },
  { char: '🐹', name: 'hamster', keywords: ['hamster', 'rodent', 'cute'], category: 'animals', subcategory: 'animal' },
  { char: '🐰', name: 'rabbit', keywords: ['rabbit', 'bunny', 'hare', 'cute'], category: 'animals', subcategory: 'animal' },
  { char: '🦊', name: 'fox', keywords: ['fox', 'animal', 'sly', 'clever'], category: 'animals', subcategory: 'animal' },
  { char: '🐻', name: 'bear', keywords: ['bear', 'animal', 'honey', 'brown'], category: 'animals', subcategory: 'animal' },
  { char: '🐼', name: 'panda', keywords: ['panda', 'bear', 'cute', 'bamboo'], category: 'animals', subcategory: 'animal' },
  { char: '🐨', name: 'koala', keywords: ['koala', 'australia', 'cute', 'tree'], category: 'animals', subcategory: 'animal' },
  { char: '🐯', name: 'tiger', keywords: ['tiger', 'cat', 'stripes', 'wild'], category: 'animals', subcategory: 'animal' },
  { char: '🦁', name: 'lion', keywords: ['lion', 'king', 'wild', 'pride'], category: 'animals', subcategory: 'animal' },
  { char: '🐮', name: 'cow', keywords: ['cow', 'bull', 'milk', 'moo'], category: 'animals', subcategory: 'animal' },
  { char: '🐷', name: 'pig', keywords: ['pig', 'piggy', 'swine', 'oink'], category: 'animals', subcategory: 'animal' },
  { char: '🐸', name: 'frog', keywords: ['frog', 'toad', 'pond', 'croak'], category: 'animals', subcategory: 'animal' },
  { char: '🐵', name: 'monkey', keywords: ['monkey', 'ape', 'banana', 'funny'], category: 'animals', subcategory: 'animal' },
];